### ISSUE TITLE
Should null discriminators be ignored for schema lookup

### ISSUE THREAD

**Issue by ctmay4** [imsweb/staging-client-java#33]
In version 2.11 the schema selection process was changed to only use the properties you passed in.  It was not intended to affect CS and TNM, but instead be an improvement for EOD.  Here are the changes.

https://github.com/imsweb/staging-client-java/commit/66f145f714b6d7596dfc2a21939dc62d3533ce3c#diff-24f9a47518db825893ecd24e071f8a36

The difference is the following lookup on CS:

```json
{
	"hist": "8000",
	"site": "C240",
	"ssf25": null
}
```

Will return no matches.  However no including the "ssf25"

```json
{
	"hist": "8000",
	"site": "C240"
}
```

returns 3 possible schemas and is how it used to work.

If we want to fix this the solution is simple.  Don't include keys that have a `NULL` value in the lookup.  Otherwise the callers will just need to know to stop passing in `NULL` values for any field involved in schema lookup.  They won't affect staging after the lookup step.

**Comment by ctmay4** [comment]
This can be accomplished with a one line change in `SchemaLookup`.

```java
    /**
     * Set the value of a single input.
     * @param key key of input
     * @param value value of input
     */
    public void setInput(String key, String value) {
        if (getAllowedKeys() != null && !getAllowedKeys().contains(key))
            throw new IllegalStateException("The input key " + key + " is not allowed for lookups");

        if (value != null)   // <--- NEW LINE HERE
            _inputs.put(key, value);
    }
```

**Comment by schusslern** [comment]
In EOD Esophagus  
C150, 8000, should not have either discriminator  
C160, 8000 needs SD1   
C150, 8020 needs SD2  
C160, 8020 needs both SD1 and SD2  
  
i'm fine with the change you are suggesting as long as it doesn't break EOD, specifically schemas like this one.

**Comment by ctmay4** [comment]
I don't think it would affect EOD.  In your example below, if you pass:

```json
{
   "site": "C150",
   "hist": "8000"
}
```

You will get a match.  If you pass:

```json
{
   "site": "C150",
   "hist": "8000",
   "sd1": null
}
```

You will not (because `null` is not `blank` so it will not match to any table).  Basically, a `null` value for a key should never be included.  The caller can ensure this happens or the library can try to make it easier if someone does pass it.  I'm fine with not doing anything now if that is what everyone wants.

**Comment by schusslern** [comment]
I’m not sure I understand the question really.

I only see this in the staging calculator and SEER*DMS.
If I start with C150, 8020, and the discriminator (to get the schema)
And then realize the hist is incorrect and change it to it
C150, 8000, and blank out the discriminator (because it doesn’t apply to hists other than 8020) would it cause a problem?
I don’t know – because I don’t know what the call actually is.

**Comment by ctmay4** [comment]
That's the point.  If RSA is smart and only passes `site` and `hist` when `sd1` is blank, then the current library works fine.  However DMS was just passing all keys all the time.  Empty keys were set to a `null` value.  That worked fine in version 2.9 but stopped working in version 2.10.  The fix is for DMS to stop passing the `null` value keys.  Mike is doing that now.  We don't have to make a change but I thought it might help future mistakes.

**Comment by ctmay4** [comment]
Looks like we will leave this as-is.  If this becomes an issue in the future this can be re-opened.
