### ISSUE TITLE
Add column to the information returned when there is a staging error

### ISSUE THREAD

**Issue by ctmay4** [imsweb/staging-client-java#54]
From Nicki:

For the diagnosis years 2004-2009, AJCC 7 was not in effect, so values for these fields are not returned.  However ERRORs for these fields ARE returned.  They show up in SEER*DMS on the staging page in the red 'error' tag.  They do not get stored as polisher errors, nor do they show up on the Edits tab on the right pane.  
But they do look like something is wrong when it really isn't.  
  
It appears that in the CS staging DLL from CDC, they didn't even attempt 7th for those diagnosis years.  But the way we structured the API, all calculations occur at one time and we blank out the unnecessary data at the end. I'd like to have the ability to ignore the AJCC 7th related errors, but I don't have enough information to identify them.  
  
The failures falling in 2 main types of errors.  

First, match not found in table with AJCC 7 in name, examples are:  

* Error: Match not found in table `ajcctnm7_stage_adenocarcinoma_xib`
* Error: Match not found in table `ajcc7_stage_ubq`

I can identify which of these can be ignored based on the table name containing `ajcctnm7` or `ajcc7`. The output field is `ajcc7_stage`.  
  
Second, matching resulted in an error in table in the AJCC 7th column, examples are:  

* Error: Matching resulted in an error in table `extension_baj`  
* Error: Matching resulted in an error in table `nodes_dev`  
* Error: Matching resulted in an error in table `mets_hae`
* Error: Matching resulted in an error in table `extension_size_high_risk_xfy`
* Error: Matching resulted in an error in table `lymph_nodes_pathologic_evaluation_xcw`

I can't identify which of these can be ignored and which are real problems solely on table name. The output fields I care about are `ajcc7_t`, `ajcc7_n`, `ajcc7_m`; but one would also see `ajcc6_t`, `ajcc6_n`, `ajcc6_m`, `t2000`, `n2000`, `m2000`, `t77`, `n77`, `m77`.  
 
I would like a way to identify all the errors that can be ignored for 2004-2009.  Current options seem to be:  

1) Have Katherine write a script to put AJCC 7, AJCC 6, SS2000 or SS1977 after ERROR: so that the final messages would be like:  
    * Error: AJCC 7 Match not found in table `ajcctnm7_stage_adenocarcinoma_xib`
    * Error: AJCC 7 Matching resulted in an error in table `mets_hae`

    However, I'm not keen on having to change the version (020550).  

2) Have Chuck change the returned items so that the data item the error relates to is included. That would be more like (I don't know everything being returned)  

    * Error: Match not found in table `ajcctnm7_stage_adenocarcinoma_xib`  | `ajcc7_stage`  
    * Error: Matching resulted in an error in table `mets_hae`  | `ajcc7_m`  

We don't want to break anything else doing this. While it isn't necessary for TNM or EOD, because they do the same calculations for all diagnosis years they apply to, it shouldn't hurt to have the information. But it would be one more element than before.  

How much work would it be, and how dangerous would it be, to implement the 2nd solution?

**Comment by ctmay4** [comment]
I've made modifications that now return the column property when there is an `ERROR` call match.  However when there is not a match in the table, the column could represent multiple column properties.  We could return the list, but I'm not sure that would solve the issue.

@schusslern how do you want to proceed?

**Comment by schusslern** [comment]
Go ahead and return all the data items from the tables where you can't find a matching row.

i think the row errors can all be identified by the table name containing ajcctnm7 or ajcc7.  On the other hand, because these are AJCC 7 tables, there is a good chance they only return AJCC 7 stage.

**Comment by ctmay4** [comment]
Ok, but just to clear, it means the `Error` entity will have a list of columns instead of a single one.  If there is an `ERROR` in a cell, the error returned will have a list of columns with only the single column.  Just pointing it out since it is a little strange.

**Comment by schusslern** [comment]
i'm okay with lists of 1 :)

**Comment by ctmay4** [comment]
@schusslern one more question.  Here is what is returned now for errors:

```json
"errors": [
	{
		"type": "STAGING_ERROR",
		"table": "lymph_nodes_clinical_eval_v0205_ajcc7_xch",
		"message": "Matching resulted in an error in table 'lymph_nodes_clinical_eval_v0205_ajcc7_xch' (000)"
	},
	{
		"type": "STAGING_ERROR",
		"table": "lymph_nodes_clinical_evaluation_ajcc6_xbi",
		"message": "Matching resulted in an error in table 'lymph_nodes_clinical_evaluation_ajcc6_xbi' (99,000)"
	},
	{
		"type": "MATCH_NOT_FOUND",
		"table": "ajcc7_stage_upw",
		"message": "Match not found in table 'ajcc7_stage_upw' (T3,<blank>,M0)"
	},
	{
		"type": "MATCH_NOT_FOUND",
		"table": "ajcc6_stage_qpf",
		"message": "Match not found in table 'ajcc6_stage_qpf' (T3,<blank>,M0)"
	}
]
```

The `columns` property will be included now that will list the fields.  Do you also want to adjust the error messages to list all the fields as well?  For `MATCH_NOT_FOUND` we are showing the input values now.  Also showing the endpoint values seems like it may be too much.  What are your thoughts?

**Comment by ctmay4** [comment]
@schusslern as to my previous comment, I think I am going to adjust the error message for `STAGING_ERROR` to include the column since there is always a single one:

```
Matching resulted in an error in table 'table_sample_first' for column 'result' (8,99)
```

I was thinking I would leave the `MATCH_NOT_FOUND` as it is since the column list could be long.

**Comment by ctmay4** [comment]
Ok, I think this is ready to be released then.
