### ISSUE TITLE
Is there a way to map NAACCR names of variables to SEER names of variables?

### ISSUE THREAD

**Issue by mgurley** [imsweb/staging-client-java#59]
For example, NAACCR Item #960:

NAACCR: TNM Clin M
SEER: Clinical M

**Comment by ctmay4** [comment]
There is no direct mapping to the NAACCR label within the staging library.  The library does contain the NAACCR item number however.  Using the NAACCR item number you can use another library (https://github.com/imsweb/layout) to complete the mapping you are looking for.  

For example, to get the NAACCR label for item 960:

```java
Layout layout = LayoutFactory.getLayout(LayoutFactory.LAYOUT_ID_NAACCR_18);
Field field = layout.getFieldByNaaccrItemNumber(960);

assertThat(field.getLongLabel()).isEqualTo("TNM Clin M");
```

Does that answer your question?

**Comment by mgurley** [comment]
That will answer my question if I can then do the following (or something like it):

assertThat(field.getShortLabel()).isEqualTo("Clinical M");

I am looking for a map that tells me that NAACCR Item #960 has a name = 'TNM Clin M' in NAACCR and a name = 'Clinical M' in SEER.

**Comment by ctmay4** [comment]
The inputs and outputs are defined in `StagingSchema` not in `StagingTable`.  For example, if you look at:

https://api.seer.cancer.gov/rest/staging/tnm/latest/schema/breast

The `inputs` key defines all the fields that are used as inputs including their NAACCR item number.  The `outputs` key also includes NAACCR item numbers when appropriate.

For example, here is what an `inputs` field looks like:

```json
{
  "key": "clin_t",
  "name": "Clinical T",
  "naaccr_item": 940,
  "table": "breast_t_70656",
  "used_for_staging": true
}
```

**Comment by mgurley** [comment]
@ctmay4 
Thanks! That was what we were looking for!
