### ISSUE TITLE
Bad type for some input columns in prostate

### ISSUE THREAD

**Issue by depryf** [imsweb/staging-client-java#6]
The JSON table referenced for SSF3 in Prostate (can't remember the table ID, sorry) has its tow last inputs (summary stage I think) defined as DESCRIPTION instead of ENDPOINT. 

This is a surprising bug because I would have thought the engine would use a column as an end-point only if it's defined as such; and if this is already true, then I would have thought some tests would have found that all the end-points defined in those columns weren't actually used by the engine...

It might be worth adding a unit test to make sure no description columns "looks like" an end-points in cstage...

Also, out of curiosity, is there any table in cstage that has more than one description column?

**Comment by ctmay4** [comment]
The table ID is ssf3_lab.  It does appear to be incorrect.  I will look further into why it didn't fail a unit test when I get back in the office.

To answer your question about descriptions, there will definitely be tables that have multiple descriptions in TNM.

**Comment by depryf** [comment]
Cool, thanks.

**Comment by ctmay4** [comment]
After looking at the table, those columns were not meant to be ENDPOINTs.  The tables are working as expected.  Closing.
