### ISSUE TITLE
Which of the libraries CS, TNM, and/or EOD supplies the NAACCR 2018 SSDI values?

### ISSUE THREAD

**Issue by VECorwin** [imsweb/staging-client-java#66]
Which of the 3 staging libraries needs to be staged in order to properly extract the allowable values for the schema applicable SSDI fields?  There is some documentation suggesting that a number of the SSDI fields were historically recorded as CS fields.  But the length of of the older CS fields does not appear to match the length of the associated SSDI field.

**Comment by ctmay4** [comment]
CS and TNM use site-specific factor fields.  For information about SSDI, only the EOD library includes that information.

https://github.com/imsweb/staging-algorithm-eod-public

**Comment by schusslern** [comment]
if you are collecting 2004-2015 cases, you can use the CS library.
This has the Site Specific Factors (SSFs), 25 slots which are all length 3.

If you are collecting 2016-2017 cases, you would use the TNM, this has the same SSFs as CS, still slots, length 3.

If you are collecting 2018 and later cases, the EOD has the SSDIs. These are separate fields per factor and the length and format are based on the needs of the factor.  While many of the SSDIs are analogous to SSFs, the allowed values have changed.  For example, for breast cancer, you would still have ER Summary, but now it is only 1 character long.

**Comment by VECorwin** [comment]
How do you tell which or how many of the discriminators are needed to specify an EOD schema, let alone how would you extract the listing of possible values for these fields?

Once a single Schema is selected/identified (with or without the use of one or more discriminators), what is the easiest method of determining which of the SSDI fields are required for the schema in question, and again how to extract the list of possible values for each required SSDI?

**Comment by ctmay4** [comment]
Schema lookup is documented in the Wiki: 

https://github.com/imsweb/staging-client-java/wiki/lookupSchema

You do your initial lookup on just site and histology.  If there are other fields required to get a single schema, the API will tell you.  There are examples of that in the Wiki.

Once you have a schema, you get get access to all the inputs with `StagingSchema.getInputs()`.  Loop over all the inputs and check `getMetaData()`.  The SSDI elements will have a "SSDI" as a metadata value.  Once you determine the input is an SSDI, you get the assocated table with valid values by called `StagingSchemaInput.getTable`.  That returns the identifier of the table.  The Wiki entry on staging  tables give information for how to use the table.

https://github.com/imsweb/staging-client-java/wiki/Tables

**Comment by ctmay4** [comment]
I assume this issue has been resolved.
