### ISSUE TITLE
EOD Algorithm lookup input issue

### ISSUE THREAD

**Issue by VECorwin** [imsweb/staging-client-java#67]
When loading a SchemaLookup object for the EOD library, some of the schemas require the "behavior" field as a discriminator, however the EodSchemaLookup class does not allow this field as an allowed input key.  How are we supposed to properly lookup only one EOD schema if the "behavior" value is the deciding factor between 2 or more, the schema Lookup process is failing to allow a single schema result in these scenarios?

One such scenario is: site=C717, histology=9591, and any value for discriminator 1.

I noticed that the "sex" field is an allowed key, but not "behavior".

**Comment by VECorwin** [comment]
As a point of clarification there are a total of 11 schema which claim to use "behavior" as at lease one of the required discriminator value(s), and 3 that claim to use the "sex" field (and yes there is one - counted in both previous numbers - that actually uses both "behavior" and "sex" values as 2 of its 3 discriminators: thus a total of 13).

**Comment by ctmay4** [comment]
You are correct.  That was an oversight and I will release and update today at some point.

If you need to get around this before I do the release, you can use `SchemaLookup` as opposed to `EodSchemaLookup` and there be no validation.

**Comment by ctmay4** [comment]
By the way, the fix for this is in the EOD project, not this one.  You can follow it here.

https://github.com/imsweb/staging-algorithm-eod-public/pull/13

I'm going to close this issue since there is nothing changing in this library.

**Comment by ctmay4** [comment]
The bugfix version is available from Maven Central now.

https://github.com/imsweb/staging-algorithm-eod-public/releases/tag/1.7.4
