### ISSUE TITLE
Consider adding support for NAACCR XML IDs

### ISSUE THREAD

**Issue by depryf** [imsweb/staging-client-java#68]
The staging framework uses its own field identifiers. 

But it also exposes NAACCR numbers in StagingSchemaInput.naaccrItem for standard NAACCR fields.

Yet the new official way to identify NAACCR items is by NAACCR XML ID, not by NAACCR numbers anymore. The numbers still work as identifier of course, and it's great to have them. But it would be very useful if that input class could also expose the XML IDs since many projects (like the validation library that runs edits) directly use and reference XML IDs, not numbers. 

That "naaccrItem" field name is a bit unfortunate; it would be nice to rename it to "naaccrItemNum" or "naaccrItemNumber". 

And then maybe add a "naaccrItemId"?

There is a direct mapping between numbers and IDs and so a simple unit test could make sure the IDs are valid and correspond to the numbers.

**Comment by schusslern** [comment]
adding the new field seems reasonable to me - i'm not sure about renaming the existing one.  Bran will need to know so he can make adjustments in Helios.  i think Chuck has to actually add the new meta data field to the structure - and hopefully he/Katherine can do something about renaming the existing field?

**Comment by schusslern** [comment]
may have to talk with Jennifer R - i feel like this would be a 2.1 release?

**Comment by depryf** [comment]
Sure. We will discuss internally. 

We don't have to rename the "naaccrItem" field; we can keep it that way and just add a "naaccrItemId" field. That will be less disruptive.

It's the usual trade off: renaming it makes the framework cleaner, but it creates work for a lot of people. We will discuss.

It will definitively need to go with a specific release, although this wouldn't affect or break anything (if we don't rename the number field).

**Comment by schusslern** [comment]
if we can do this before Sept we could release it - may make some others lives easier in the long run

**Comment by ctmay4** [comment]
Is there any reason to continue supporting the number?  It is not used by the library and is just informational.  We could just convert the numbers to XML identifiers.

**Comment by schusslern** [comment]
i find the numbers helpful when names are similar and i believe registrars do as well.  i would not want to get rid of them

**Comment by ctmay4** [comment]
Ok; it just seems like numbers are the old way and IDs are the new way.  Seems odd to support them both long term.  For example, once the flat is completely gone and new fields are added will they continue to give them numbers in addition to the identifier?

**Comment by schusslern** [comment]
as far as i know they plan to continue to assign numbers.  (its a lot like edits- they have names in text, but they can be very confusing and the edit number - IF26 or whatever - is much clearer; also faster to type)

**Comment by depryf** [comment]
Numbers are not going anywhere. Many software rely on them to uniquely identify the items, instead of the new XML IDs. And that will probably never change. 

I like to say that the XML ID are the "official IDs", mainly because the XML IDs are required to appear in the XML data files while the numbers are optional.

But the truth is they are both official and legit ways to uniquely identify items. And outside of NAACCR XML, the numbers are much more used than the XML IDs.

**Comment by depryf** [comment]
Yes, that seems right to me!

**Comment by ctmay4** [comment]
Just to be clear, the NAACCR XML identifiers should be set for CS, TNM and EOD.  I think Katherine should be able to do that in a script, but we should probably have them set everywhere.

**Comment by depryf** [comment]
That can definitively be done with a script.

**Comment by kirbykn** [comment]
That sounds good to me.

**Comment by schusslern** [comment]
what are you going to do for version numbers for those? (CS and TNM)

**Comment by ctmay4** [comment]
We have minor version numbers that don't have anything to do with the algorithm version.  For example, the current CS version is `02.05.50.3`.  The new one will be `02.05.50.4`

**Comment by ctmay4** [comment]
I'm integrating the new version in SEER*API.  I have a question.  Take a look at the "testis" schema.

https://staging.seer.cancer.gov/eod_public/schema/1.7/testis/?breadcrumbs=(~schema_list~)

The first input is "Year of Diagnosis".  The NAACCR item number is 390.  When I looked into NAACCR XML identifiers I saw that there is only a `dateOfDiagnosis` and not a specific year field.

```xml
<Item naaccrId="dateOfDiagnosis">20170715</Item>
```

Is this an issue?

**Comment by depryf** [comment]
NAACCR made the decision (a long time ago) to only deal with dates and not their individual parts.

And so the parts are not valid NAACCR data items on their own. 

Yet this framework needs to use only the year, not the full date. 

And so we had to compromise.

It's already an issue now with the number; 390 is not the year of diagnosis, it's the date of diagnosis. Adding the XML ID is not different. It's wrong, but everyone should understand why it's done that way.

The only problem with this is if someone provides a full date for that input. Technically this is the "correct" thing to do following the item number/ID. But clearly the framework expects only the year. I don't know if you have validation in place for the year (making sure its 4 digits), or if you have code that would also accept 6 or 8 digits and just take the first 4 (that would be a good idea).

Like I said, that's a small issue that already exists now with the numbers and I don't think we are making it worse by adding the XML ID.

**Comment by ctmay4** [comment]
Ok, just wanted to make sure.  I will get SEER*API updated soon and pass this along to Helios.
