### ISSUE TITLE
Handle case of key being an input and an output field

### ISSUE THREAD

**Issue by ctmay4** [imsweb/staging-client-java#75]
When staging a case, one of the last steps is to remove any field from the results that are part of the input.  

```java
// remove the original input keys from the resulting context;  in addition, we want to remove any input keys
// from the resulting context that were set with a default value; to accomplish this remove all keys that are
// defined as input in the selected schema
for (Entry<String, String> entry : data.getInput().entrySet())
    context.remove(entry.getKey());
for (StagingSchemaInput input : schemas.get(0).getInputs())
    context.remove(input.getKey());
```

This needs to be adjusted so that it will not remove input fields if they are ALSO defined as an output field.  There is a real-world case of this in `lymphoma_cll_sll` for the upcoming EOD 2.1.

Adding @schusslern

**Comment by schusslern** [comment]
i don't think i need it relaxed at this time.  there is default value and i don't really want an invalid value the way i did for the EOD Derived fields.  i'll try to remember this is true tho, in case something comes u p later.
